image: maven:3.6.2-jdk-11

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

before_script:
  ##
  ## Install ssh-agent if not already installed, it is required by Docker.
  ## (change apt-get to yum if you use an RPM-based image)
  ##
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

  ##
  ## Run ssh-agent (inside the build environment)
  ##
  - eval $(ssh-agent -s)

  ##
  ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
  ## We're using tr to fix line endings which makes ed25519 keys work
  ## without extra base64 encoding.
  ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
  ##
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

  ##
  ## Create the SSH directory and give it the right permissions
  ##
  - echo "$SSH_PRIVATE_KEY" > key.prv
  - chmod 600 key.prv
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

stages:
  - build
  - test
  - deploy


cache:
  paths:
    - .m2/repository
    - target/

build_job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS  compile

test_job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS  test -P Unit

deploy-master:
  stage: deploy
  script:  ssh -i key.prv  -oStrictHostKeyChecking=no usuario@virtual.lab.inf.uva.es -p 20201 "cd tfg-sonarvensim && git reset --hard && git checkout master && git pull origin master&& mvn package -DskipTests
          && cp target/sonar-vensim-1.0-SNAPSHOT.jar  ../sonarqube-8.0/extensions/plugins/sonar-vensim-1.0-SNAPSHOT.jar
          && sh ../sonarqube-8.0/bin/linux-x86-64/sonar.sh restart && exit"
  only:
    - master

deploy-develop:
  stage: deploy
  script:  ssh -i key.prv  -oStrictHostKeyChecking=no usuario@virtual.lab.inf.uva.es -p 20201 "cd tfg-sonarvensim && git reset --hard && git checkout develop && git pull origin develop&& mvn package -DskipTests
          && cp target/sonar-vensim-1.0-SNAPSHOT.jar  ../sonarqube-8.0/extensions/plugins/sonar-vensim-1.0-SNAPSHOT.jar
          && sh ../sonarqube-8.0/bin/linux-x86-64/sonar.sh restart && exit"
  only:
    - develop
