image: maven:3.5.0-jdk-8-alpine

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"


stages:
  - build
  - test


cache:
  paths:
    - .m2/repository
    - target/

build_job:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS  compile

test_job:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS  test


